version: '3'
services:
  orderly_server:
    build:
      context: ./server
    ports:
      - "8003:8003"
    container_name: orderly_server

  orderly_client:
    build:
      context: ./client
    ports:
      - "3003:3003"
    container_name: orderly_client
