version: '3'
services:
  gateway_fitness_server:
    build:
      context: ./server
    ports:
      - "8003:8003"
    container_name: gateway_fitness_server

  gateway_fitness_client:
    build:
      context: ./client
    ports:
      - "3003:3003"
    container_name: gateway_fitness_client
